name: Bump Package Version
on:
  workflow_call:
    inputs:
      type:
        required: false
        type: string
        default: ${{(startsWith(github.event.head_commit.message, '(minor)') && 'minor') || (startsWith(github.event.head_commit.message, '(major)') && 'major') || 'patch'}}

jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Git Config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Version Bump
        run: npm version ${{ inputs.type }} --workspace=yaml-json-converter-vscode --no-package-lock # Not ideal, but turborepo is broken https://github.com/vercel/turborepo/issues/1749

      - name: Store New Version
        run: echo "NEW_VERSION=$(npm run version --workspace=yaml-json-converter-vscode --silent)" >> $GITHUB_ENV

      - name: Push Bump
        run: git add . && git commit -m "🚀 Release v${{ env.NEW_VERSION }} (${{ inputs.type }})" && git push
