name: Push Event
on:
  push:
    branches: [master]
  pull_request:
    branches: "*"
  workflow_dispatch:

jobs:
  build-test:
    name: 🛠 Build and Test
    uses: ./.github/workflows/build-test.yml
  bump-version:
    name: 📈 Bump Package Version
    if: github.ref == 'refs/heads/master'
    needs: build-test
    uses: ./.github/workflows/bump-version.yml
    secrets: inherit
    with:
      type: ${{(startsWith(github.event.head_commit.message, '(minor)') && 'minor') || (startsWith(github.event.head_commit.message, '(major)') && 'major') || 'patch'}}
  publish:
    name: 🚀 Publish
    if: github.ref == 'refs/heads/master'
    needs: bump-version
    uses: ./.github/workflows/publish.yml
    secrets: inherit
