name: Publish
on:
  workflow_call:
    inputs:
      workspace:
        type: string
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: ./packages/yaml-json-converter-vscode/dist
