name: Publish
on:
  workflow_call:
    inputs:
      workspace:
        type: string
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output-${{ inputs.workspace }}
          path: ./packages/${{ inputs.workspace }}/dist

      - name: Publish
        run: npm publish --access public --workspace=${{ inputs.workspace }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
